kibana:
  image: kibana
  command: kibana
  links:
    - elasticsearch
  ports:
    - "5601:5601"
logstash-shipper:
  image: logstash
  command: logstash -f /config-dir/shipper.config
  volumes: 
    - ./config/logstash:/config-dir  
  links:
    - redis
logstash-indexer:
  image: logstash
  command: logstash -f /config-dir/indexer.config
  volumes: 
    - ./config/logstash:/config-dir  
  links:
    - elasticsearch
    - redis
elasticsearch:
  image: elasticsearch
redis:
  image: tutum/redis
  environment:
    - REDIS_PASS=123
