version: '3'
services:

  consul:
    image: consul:1.5.1
    container_name: consul
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    # volumes:
      # - ./data/consul/data:/consul/data
      # - ./consul/config:/consul/config
    command: "agent -server -bootstrap -ui -client=0.0.0.0"

  vault:
    image: vault:1.1.3
    container_name: vault
    hostname: vault
    environment:
      VAULT_ADDR: http://localhost:8200
    ports:
      - "8200:8200"
    volumes:
      - ./config/vault:/config
      - ./config/vault/policies:/policies
      - ./data/vault/logs:/vault/logs
      - ./data/vault/file:/vault/file
    entrypoint: vault server -config=/config/config.hcl

