version: '2'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    image: web-nginx
    ports: 
      - 0.0.0.0:80:80
    volumes_from:
      - web-data
    depends_on:
      - php-fpm
      - web-data
    networks:
      - net1

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    image: web-php
    ports: 
      - 0.0.0.0:9000:9000
    volumes_from:
      - web-data
    depends_on:
      - web-data
    networks:
      net1:
        aliases:
          - php-fpm

  web-data:
    build:
      context: .
      dockerfile: Dockerfile-base
    image: web-base
    volumes:
      - ./www:/home/wwwroot/www
      - ./log:/var/log

networks:
  net1:
