FROM alpine:3.3

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN mkdir /home/wwwroot/www -p && \
    mkdir /var/log -p

VOLUME /home/wwwroot/www /var/log

CMD ["true"]
